project:
  type: website
  output-dir: docs

execute:
  echo: false

website:
  title: "Geriatrics Evidence Synthesis"
  search:
    location: navbar
    limit: 100
  favicon: favicon.png
  navbar:
    background: primary
    search: true
    pinned: true
    left:
      - href: index.html
        text: Home
      - href: balance_tables.html
        text: "Balance Tables"
      - href: soe_gt.html
        text: GRADE
      - text: Key Question
        menu:
          - href: kq1.html
            text: "Expanded Preop Evaluation"
          - href: kq2.html
            text: "Prehabilitation"
          - href: kq3.html
            text: "Neuraxial versus General Anesthesia"
          - href: kq4.html
            text: "TIVA versus Inhaled Anesthesia"
          - href: kq5.html
            text: "Potentially Inappropriate Medications"
          - href: kq6.html
            text: "Delirium Prophylaxis"
      - text: Appendix
        menu:
          - href: evidence_tables.html
            text: "Study-level evidence tables"
          - href: outcome_rankings.html
            text: "Outcome rankings"
          - href: summary_kq3.html
            text: "Summary: Neuraxial versus General Anesthesia"
          - href: protocol.html
            text: "Draft protocol"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

