project:
  type: website
  output-dir: docs
  preview:
    watch-inputs: false
  render:
    - "*.qmd"
    - "!timing-NMA.qmd"
    - "!workflow.qmd"

execute:
  echo: false

website:
  title: "Geriatrics Anesthesia Evidence Synthesis"
  search:
    location: navbar
    limit: 100
  favicon: favicon.png
  navbar:
    background: primary
    search: true
    pinned: true
    left:
      - href: index.html
        text: Home
      - href: balance_tables.html
        text: "Balance Tables"
      - href: soe_gt.html
        text: GRADE
      - text: Key Question
        menu:
          - href: kq1.html
            text: "Expanded Preop Evaluation"
          - href: kq3.html
            text: "Neuraxial versus General Anesthesia"
          - href: kq4.html
            text: "TIVA versus Inhalation Anesthesia"
          - href: kq5.html
            text: "Potentially Inappropriate Medications"
          - href: kq6.html
            text: "Delirium Prophylaxis"
      - text: Appendix
        menu:
          - href: summary_kq1.html
            text: "Expanded Preoperative Evaluation: study/patient characteristics"
          - href: summary_kq3.html
            text: "Neuraxial versus General Anesthesia: study/patient characteristics"
          - href: summary_kq4.html
            text: "TIVA versus Inhalation Anesthesia: study/patient characteristics"
          - href: summary_kq6.html
            text: "Delirium Prophylaxis: study/patient characteristics"
          - href: evidence_tables.html
            text: "Study-level evidence tables"
          - href: outcome_rankings.html
            text: "Outcome importance rankings"
          - href: protocol.html
            text: "Draft protocol"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

