project:
  type: website
  output-dir: docs
website:
  title: "Geriatrics Evidence Synthesis"
  search:
    location: navbar
    limit: 100
  favicon: favicon.png
  navbar:
    background: primary
    search: true
    pinned: true
    left:
      - href: index.html
        text: Home
      - href: soe_gt.html
        text: GRADE
      - text: Key Question
        menu:
          - href: kq1.html
            text: "[Screening: Expanded Preop & Postop Delirium"
          - href: kq2.html
            text: "Prehabilitation"
          - href: kq3.html
            text: "Regional vs. Regional Anesthesia"
          - href: kq4.html
            text: "Intravenous vs. Inhaled Anesthesia"
          - href: kq5.html
            text: "Potentially Inappropriate Medications"
          - href: kq6.html
            text: "Delirium Prophylaxis"
      - text: Appendix
        menu:
          - href: evidence_tables.html
            text: "Study-level evidence tables"
          - href: outcome_rankings.html
            text: "Outcome rankings"
          - href: protocol.html
            text: "Draft protocol"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

