---
title: "Evidence Tables"
editor: source
toc-title: "Study Design"
toc-location: "left"
tbl-cap-location: "top"
page-layout: full
css: styles.css
navbar:
    background: primary
    search: true
    pinned: true
    copy-button: true
tables:
      style: Table
      caption:
        pre: "Table "
        sep: " -- "
bibliography: "bib/allrefs.bib"
csl: jama.csl
link-citations: false
nocite: '@*'
---

```{css, echo = FALSE}
:target {  /* fix target location so caption appears */
    display: block;
    position: relative;
    top: -105px;
    visibility: display;
}

</style>
```


<!-- setup -------------------------------------------- (2022-12-24 16:56) @ --->

```{r read_data}
#| include: false
source("code/load_data.R")
```

```{r evidenceTables}
# incl excl enrolled summary
evidence_tables <- study_char_dat |> 
  select(refid, author, year, study, n_enroll, include, exclude, results, design_f_lab, comment) |> 
  mutate(
    year = str_extract(study, "\\d{4}\\w?$"),
    study = glue("{author}<br/>{year}<span><a id='{refid}'></a></span>"),
    include = firstup(include),
    exclude = firstup(exclude),
    results = firstup(results),
    results = if_else(!str_detect(results, "\\.$"), paste0(results, "."), results),
    include = if_else(!str_detect(include, "\\.$"), paste0(include, "."), include),
    include = str_replace_all(include, ">=", "≥"),
    include = str_replace_all(include, "<=", "≤"),
    exclude = str_replace_all(exclude, ">=", "≥"),
    exclude = str_replace_all(exclude, "<=", "≤"),
    exclude = if_else(!str_detect(exclude, "\\.$"), paste0(exclude, "."), exclude),
    incl_excl = paste0("**Include:** ", include, "<br/>", "**Exclude:** ", exclude),
    incl_excl = str_replace(incl_excl, "NA", " Not specified."),
  ) |> 
  relocate(study, .after = refid) |> 
  replace_na(list(comment = "")) 

# trial refids
rand_trial_refid <- study_char_dat |> 
  filter(design_f %in% c("rct", "cluster", "crossover")) |> 
  pull(refid)

# nr trial refids
nr_trial_refid <- study_char_dat |> 
  filter(design_f %in% c("nr_trial")) |> 
  pull(refid)

# quasi experimental refids
quasi_refid <- study_char_dat |> 
  filter(design_f %in% c("quasi_exp")) |> 
  pull(refid)

# observational refids
obs_refid <- study_char_dat |> 
  filter(!design_f %in% c("rct", "nr_trial", "cluster", "crossover", "quasi_exp")) |> 
  pull(refid)

study_char_dat |> tabyl(design_f)

# later add study arm data
# study_arm_dat_trial <- study_arm_dat |> 
#   filter(refid %in% trial_refid)
  # filter((refid %in% kq5_refid) & (refid %in% trial_refid))

```

<!-- ## Key Question 5 -->

```{r evidence_table_template}
evidence_tables_function <- function(refid_select) {
evidence_tables |>
  filter(refid %in% refid_select) |>
  arrange(design_f_lab, study) |>
  select(study, n_enroll, incl_excl, results, comment) |>
  # group_by(design_f_lab) |>
  gt(id = "one") |> 
  cols_label(
    study = "Study",
    n_enroll = "Enrolled",
    incl_excl = "Inclusion/Exclusion Criteria",
    results = "Results",
    comment = "Note"
  ) |> 
  cols_width(
    study ~ "80px",
    n_enroll ~ "50px",
    incl_excl ~ "300px",
    results ~ "300px",
    comment ~ "160px"
  ) |> 
    cols_align(
    align = "left",
    columns = study
  ) |>
  cols_align(
    align = "center",
    columns = n_enroll
  ) |>
  tab_style(
    style = cell_text(size = "12px"),
    locations = cells_body(columns = everything())) |> 
  fmt_markdown(columns = c(study, incl_excl, results, comment)) |> 
    tab_style(
    style = "vertical-align:top",
    locations = cells_body(columns = everything())
  ) |> 
  gt_theme_mg() |> 
    opt_css(
      css = "
      p {
      line-height: 1.5;
      }
    "
    )
}
```

<br/><br/>

## Randomized Clinical Trials


```{r}
evidence_tables_function(rand_trial_refid)
```

<br/><br/>

## Nonrandomized Trials

```{r}
evidence_tables_function(nr_trial_refid)
```

<br/><br/>

## Before-after & Time Series

```{r}
evidence_tables_function(quasi_refid)
```

<br/><br/>

## Observational

```{r}
evidence_tables_function(obs_refid)
```

<br/>

# References {#references}
