---
title: "KQ 2 Prehabilitation"
editor: visual
toc-title: "Prehabilitation"
toc-location: "left"
tbl-cap-location: "top"
page-layout: full
css: styles.css
tables:
      style: Table
      caption:
        pre: "Table "
        sep: " -- "
# bibliography: "bib/kq1.bib"
# csl: jama.csl
# link-citations: false
# nocite: '@*'
---

## Key Question

Among patients 65 years or older \[geriatric\] anticipating surgery and anesthesia, do interventions targeted at improving physical function, cognition, and nutritional status before surgery ("prehabilitation") improve postoperative outcomes?

<!-- setup -------------------------------------------- (2022-12-24 16:56) @ --->

```{r, read_data}
#| include: false
source("code/load_data.R")
```

<!-- kq5..._dat files --------------------------------- (2022-12-28 08:41) @ --->

```{r, data}
# note working file not renamed
study_char_dat <- study_char_dat |> 
  filter(refid %in% kq1_refid) |> 
  arrange(design_f)

study_arm_dat <- study_arm_dat |> 
  filter(refid %in% kq1_refid) |> 
  arrange(design_f)
```

<!-- ## Outcome Importance Rankings -->

<!-- <font size = 4> `r table_ref()` Rankings of the 5 most important outcomes (11 respondents). </font> -->

```{r, outcome_priority}
#| include: true
#| eval: false
outcome_dat <- rankings("KQ2")
outcome_tab(outcome_dat, 11)
```
