---
title: "KQ 3 Regional vs. General Anesthesia"
editor: source
toc-title: "Regional vs. General Anesthesia"
toc-location: "left"
tbl-cap-location: "top"
page-layout: full
css: styles.css
tables:
      style: Table
      caption:
        pre: "Table "
        sep: " -- "
# bibliography: "bib/kq3.bib"
# csl: jama.csl
# link-citations: yes
# nocite: '@*'
---

## Key Question

Among patients 65 years or older \[geriatric\] undergoing surgery, does regional anesthesia as the primary anesthetic technique improve postoperative outcomes compared with general anesthesia?

<!-- setup -------------------------------------------- (2022-12-24 16:56) @ --->

```{r, read_data}
#| include: false
source("code/readfiles_geri_2022-11-16.R")
study_char_dat <- data_kq(study_char_dat, kq3_refid)
study_arm_dat <- data_kq(study_arm_dat, kq3_refid)
contin_dat <- data_kq(contin_dat, kq3_refid)
dichot_dat <- data_kq(dichot_dat, kq3_refid)
likert_dat <- data_kq(likert_dat, kq3_refid)
```

<!-- kq5..._dat files --------------------------------- (2022-12-28 08:41) @ --->

```{r, data}
# note working file not renamed
study_char_dat <- study_char_dat |> 
  filter(refid %in% kq3_refid) |> 
  arrange(design_f)

study_arm_dat <- study_arm_dat |> 
  filter(refid %in% kq3_refid) |> 
  arrange(design_f)
```

## Outcome Importance Rankings

<font size = 4> `r table_ref()` Rankings of the 5 most important outcomes (10 respondents). </font>

```{r, outcome_priority}
#| include: true
outcome_dat <- rankings("KQ3")
outcome_tab(outcome_dat)
```
