---
title: "Outcome Priority Rankings"
editor: source
toc-title: "Outcome Priority Rankings"
toc-location: "left"
toc_float: 
  collapsed: true
tbl-cap-location: "top"
page-layout: full
css: styles.css
tables:
      style: Table
      caption:
        pre: "Table "
        sep: " -- "
---


```{r}
#| message: false
#| echo: false
source("code/load_data.R")
```

## For all included key questions 

<font size = 4> `r table_ref()`</font> Rankings for the 5 most important outcomes across 7 key questions (11 respondents; maximum 77 for each outcome rank or any top 5 ranking).

```{r}
## key questions 1-6 & 8 --------------------------------------- (2023-01-24 11:48) @----
# function for outcome priority table by kq
outcome_tab_all <- function(outcome_dat, responses) {
  reactable(
    outcome_dat,
    pagination = FALSE,
    # highlight = TRUE,
    defaultSorted = "any_top_5",
    defaultSortOrder = "desc",
    defaultColDef = colDef(
      cell = data_bars(outcome_dat,
                       box_shadow = TRUE,
                       force_outside = c(1, 77),
                       bar_height = 12,
                       max_value = responses
                       # fill_color = "#B22215"
      ),
      style = cell_style(outcome_dat,
                         font_size = "11px",
      )
    ),
    columns = list(
      outcome = colDef(name = "Outcome", width = 200),
      rank1 = colDef(name = "Rank 1", width = 80, headerClass = "header", align = "center"),
      rank2 = colDef(name = "Rank 2", width = 80, headerClass = "header", align = "center"),
      rank3 = colDef(name = "Rank 3", width = 80, headerClass = "header", align = "center"),
      rank4 = colDef(name = "Rank 4", width = 80, headerClass = "header", align = "center"),
      rank5 = colDef(name = "Rank 5", width = 80, headerClass = "header", align = "center"),
      any_top_5 = colDef(
        name = "Any", width = 80, headerClass = "header", align = "center",
        cell = data_bars(
          outcome_dat,
          force_outside = c(1, 77),
          box_shadow = TRUE,
          bar_height = 12,
          max_value = responses,
          fill_color = "#B22215"
        )
      )
    ),
    theme = reactableTheme(
      borderColor = "#dfe2e5",
      stripedColor = "#f6f8fa",
      highlightColor = "#f0f5f9",
      cellPadding = "0px 0px"
    ),
    compact = TRUE,
    class = "priority-tbl"
  )
}

# read data for all kq
priority_dat <- readxl::read_xlsx("data/OutcomeRankingRawData_2023-01-23_edit.xlsx", range = "A1:S89", sheet = "data") |>
  fill(kq) |>
  # exclude kq7 not being addressed
  filter(kq != 7) |>
  mutate(id = paste0(kq, "-", id))

# function to tally the number by rank 1, 2, 3, 4, 5
rankings_all <- function(priority) {
  priority_dat |>
    # group_by(kq) |>
    summarise(across(3:19, ~ sum(.x == priority, na.rm = TRUE)), .names = "{.col}") |>
    mutate(rank = priority)
}

rankings_dat <- bind_rows(rankings_all(1), rankings_all(2), rankings_all(3), rankings_all(4), rankings_all(5)) |>
  select(-.names)

rankings_dat <- transpose_tibble(rankings_dat, col_names = rank, id_col = "outcomes") |>
  rename_with(.fn = ~ paste0("rank", .)) |>
  rename(outcome = rankoutcomes) |>
  mutate(across(rank1:rank5, as.numeric),
    any_top_5 = rank5 + rank4 + rank3 + rank2 + rank1
  )

# rankings_dat |>
#   summarise(across(rank1:rank5, sum))

outcome_tab_all(rankings_dat, 77)
```
