---
title: "Strength of Evidence"
editor: source
toc-title: "Delirium Prophylaxis"
toc-location: "left"
toc-depth: 4
toc_float: 
  collapsed: false
tbl-cap-location: "top"
page-layout: full
css: styles.css
tables:
      style: Table
      caption:
        pre: "Table "
        sep: " -- "
# bibliography: "bib/kq6.bib"
# csl: jama.csl
# link-citations: no
# nocite: '@*'
---

```{r preliminaries}
#| include: false
## preliminaries -------------------------------------- (2022-11-16 11:49) @----
library(conflicted)
library(janitor)
library(htmltools)
library(gt, quietly = TRUE)
library(gtsummary)
library(gtExtras)
library(glue)
library(tidyverse)
conflicts_prefer(dplyr::filter)
knitr::opts_chunk$set(echo = FALSE)
source("code/functions_geri_2022-11-16.R")

```

```{r}
# grade footnote
vlow <-  '<span><span class="quality-sign">⨁</span><span class="quality-sign">◯</span><span class="quality-sign">◯</span><span class="quality-sign">◯</span>'
low <- '<span><span class="quality-sign">⨁</span><span class="quality-sign">⨁</span><span class="quality-sign">◯</span><span class="quality-sign">◯</span>'
mod <- '<span><span class="quality-sign">⨁</span><span class="quality-sign">⨁</span><span class="quality-sign">⨁</span><span class="quality-sign">◯</span>'
high <- '<span><span class="quality-sign">⨁</span><span class="quality-sign">⨁</span><span class="quality-sign">⨁</span><span class="quality-sign">⨁</span>'
grade_foot <- paste0("Very low: ", vlow, "; Low: ", low, "; Moderate: ", mod, "; High: ", high, ".")

# TODO: add functions to read data
```

# Delirium Prophylaxis

```{r soeKq6Data}
#| include: false
## soeKq6Data (updated 2022/01/20 09:18) ----------------------------------
col_types_soe <- c("numeric", rep("text", 5), "numeric", rep("text", 19))
soe_kq6.dat <- readxl::read_xlsx("data/soe_2023-03-11.xlsx", range = "A1:Z4", sheet = "soe_kq6", col_types = col_types_soe) |>
  clean_names() |>
  mutate(
    n_s = paste0(n_studies, " <br/>(", n_pts, ")"),
    n = paste0(n, outcome),
    # outcome = tools::toTitleCase(outcome) |>
    # outcome = str_to_sentence(outcome),
    out_import = case_when(
      out_import == "Limited" ~ "+",
      out_import == "Important" ~ "++",
      out_import == "Critical" ~ "+++"
    )
  )

## (updated 2021/11/17 11:44) soe_summary ---------------------------------
soe_summary <- soe_kq6.dat |>
  select(n, comparison, outcome, n_s, grade, acc, out_import, summary, result_links) |>
  mutate(
    grade = case_when(
      grade == "very low" ~ vlow,
      grade == "low" ~ low,
      grade == "moderate" ~ mod, 
      grade == "high" ~ high
    )
  )

## (updated 2021/11/17 11:44) domain_summary ------------------------------
domain_summary <- soe_kq6.dat |> 
  select(n, comparison, outcome, design, n_studies, n_pts, rob, consist, direct, prec, other, summary, ends_with("foot")) |> 
  mutate(design = str_to_sentence(design),
         consist_foot = ifelse(!grepl("\\.$", consist_foot) & !is.na(consist_foot), paste0(consist_foot, "."), consist_foot),
         direct_foot  = ifelse(!grepl("\\.$", direct_foot ) & !is.na(direct_foot ), paste0(direct_foot , "."), direct_foot ),
         prec_foot    = ifelse(!grepl("\\.$", prec_foot   ) & !is.na(prec_foot   ), paste0(prec_foot   , "."), prec_foot   ),
         rob_foot     = ifelse(!grepl("\\.$", rob_foot    ) & !is.na(rob_foot    ), paste0(rob_foot    , "."), rob_foot    ),
         other_foot   = ifelse(!grepl("\\.$", other_foot  ) & !is.na(other_foot  ), paste0(other_foot  , "."), other_foot  ),
         across(ends_with("foot"), ~ firstup(.x))
         ) 

```


<br/>

### Strength of Evidence Ratings

<br/>

<font size = 4> `r table_ref()` Strength of evidence for outcomes relevant to delirium prophylaxis. </font>

```{r kq6SOE_gt}
#| include: true
#| echo: false

## kq6SOE (updated 2022/01/20 15:00) --------------------------------------
soe_summary |>
  mutate(across(grade:result_links, ~ replace_na(., ""))) |> 
  gt(id = "one") |>
  cols_hide(c(n, comparison)) |>
  cols_label(
    outcome = "Outcome",
    n_s = "Studies (Pts)",
    grade = "GRADE",
    acc = "ACCF AHA",
    out_import = "Importance",
    summary = "Summary",
    result_links = "Result Detail"
  ) |>
  fmt_markdown(columns = c(outcome, n_s, grade, summary, result_links)) |>
  tab_style(style = cell_text(align = "center"), locations = cells_column_labels(columns = c(n_s, grade, acc, out_import, summary))) |>
  tab_style(style = cell_text(align = "center"), locations = cells_body(columns = c(n_s, grade, acc, out_import, summary))) |>
  tab_style(style = cell_text(align = "left"), locations = cells_body(columns = c(outcome, summary, result_links))) |>
  gt_theme_mg() |>
  cols_width(
    outcome ~ px(120),
    n_s ~ px(85),
    grade ~ px(60),
    acc ~ px(60),
    out_import ~ px(80),
    summary ~ px(400),
    result_links ~ px(100)
  ) |>
  tab_footnote("Pts: patients; GRADE: Grades of Recommendation, Assessment, Development, and Evaluation; ACCF/AHA: American College of Cardiology Foundation/American Heart Association; RR: risk ratio.") |>
  tab_footnote(md(grade_foot), locations = cells_column_labels(columns = grade)) |>
  tab_footnote("+ Limited; ++ Important; +++ Critical.", locations = cells_column_labels(columns = out_import))


```




