---
title: "Study/Patient Characteristics Neuraxial versus General Anesthesia"
date: "`r format(Sys.time(), '%d %B, %Y (%H:%M)')`"
editor: source
toc-title: "**Neuraxial versus General Anesthesia**"
toc-location: "left"
cap-location: "top"
toc-depth: 3
page-layout: full
css: styles.css
tables:
      style: Table
      caption:
        pre: "Table "
        sep: " -- "
---

```{r read_data}
#| include: false
source("code/load_data.R")

# exclude linked references
linked_publications <- linked_refids |> 
  filter(refid %in% kq3_refid) |> 
  filter(!is.na(refid_to_link_to)) |> 
  pull(refid)

kq3_refid <- kq3_refid[!kq3_refid %in% linked_publications] # 2024-03-11 n = 38

study_char_dat <- data_kq(study_char_dat, kq3_refid)

# ortho only hip fx ortho_hipfx_only_refid
ortho_hipfx_only_refid <- ortho_proc |> 
  filter(ortho == "HipFx") |> 
  pull(refid)

## VARIABLE: kq3_anesth_neur, kq3_anesth_reg, kq3_anesth_gen, kq3_anesth_neur_type, kq3_anesth_gen_type — anesthetic and type, no specifics recorded for regional
study_arm_dat <- data_kq(study_arm_dat, kq3_refid) |>
  # exclude Bielka 2021 arm 3 (block)
  filter(!(study == "Bielka 2021" & arm_id == 3)) |> 
  # delete anesthetic variables not relevant (avoid potential confusion)
  select(-c(inhalation:anes_ns)) |>
  mutate(arm = arm_kq3_reg_gen) |>
  relocate(arm, .before = arm_kq3_reg_gen) |>
  mutate(
    kq3_anesth_neur = ifelse(if_any(c(kq3_reg_spinal, kq3_reg_epidural, kq3_reg_cse), ~ !is.na(.x)), "Neuraxial", NA),
    kq3_anesth_gen = ifelse(!is.na(kq3_gen_type), "General", NA),
    kq3_anesth_neur_type =
      case_when(
        !is.na(kq3_reg_spinal) ~ "Spinal",
        !is.na(kq3_reg_epidural) ~ "Epidural",
        !is.na(kq3_reg_cse) ~ "CSE"
      ),
    kq3_anesth_gen_type = kq3_gen_type,
    arm = factor(arm, levels = c("general", "regional"), labels = c("Gen", "Neur"))
  ) |>
  relocate(kq3_anesth_neur:kq3_anesth_gen_type, .before = kq3_gen_type)

# get refids to include so that linked studies are not double counted
no_linked_refids <- study_char_dat |> 
  group_by(linked_references_all_refid) |>
  filter(n_enroll == max(n_enroll)) |>
  slice(1) |> 
  pull(refid)

asa_class <- asa_combine |>
  mutate(asa = str_trim(asa_ps_incl)) |>
  select(refid, asa) |>
  slice(1, .by = "refid")

```

## Randomized Clinical Trials

<font size = 4> `r table_ref()` Study and patient characteristics. </font>

```{r dex_rct}
#| layout: [[35, 30, 35]]

summary_study_char_tab_rct(kq3_refid)

summary_surg_tab_rct(kq3_refid)

## table data ----
pt_char_tab <- study_arm_dat |>
  filter(refid %in% pt_char_tab_refids_rct(kq3_refid)) |> 
  mutate(
    wgt = arm_n / sum(arm_n, na.rm = TRUE),
    N = sum(arm_n),
    .by = refid
  ) |> 
  group_by(refid) |>
  summarize(
    across(
      c(
        age_mean,
        age_med,
        female_perc,
        white,
        black,
        asian,
        bmi_m,
        bmi_med,
        pre_mmse_m,
        pre_mmse_med,
        # living_independent,
        # living_dependent,
        # housing_home,
        # housing_assisted,
        cog_imp,
        # malnourish,
        dm,
        cardiac,
        # cancer,
        # ortho,
        # gi,
        # neuro,
        # pulm,
        # endo,
        # renal,
        # hepatic
      ),
      ~ pt_sum(.x, wgt)
    ),
    N = sum(arm_n)
  ) |>
  mutate(
    age_mean_med = coalesce(age_mean, age_med),
    bmi_mean_med = coalesce(bmi_m, bmi_med),
    pre_mmse_mean_med = coalesce(pre_mmse_m, pre_mmse_med),
  ) |>
  select(-c(bmi_m, bmi_med, pre_mmse_m, pre_mmse_med, age_mean, age_med)) |>
  left_join(asa_class, by = "refid")

## summary table ----
pt_char_tab |>
  select(age_mean_med, bmi_mean_med, female_perc, asa, white, black, asian, pre_mmse_mean_med, cog_imp, dm, cardiac) |>
  mutate(
    # asian = ifelse(asian == 100, "100%", NA),
    asa = ifelse(asa == "NR", NA, asa),
  ) |>
  tbl_summary(
    label = list(
      age_mean_med = "Age (mean/med)",
      bmi_mean_med = "BMI (mean/med)",
      female_perc = "Female (%)",
      asa = "ASA Physical Status, N (%)",
      white = "White (%)",
      black = "Black (%)",
      asian = "Asian (%)",
      # living_independent = "Lives Independently (%)",
      # living_dependent = "Lives Dependent (%)",
      # housing_home = "Living at Home (%)",
      # housing_assisted = "Assisted Living (%)",
      cog_imp = "Cognitive Impairment (%)",
      pre_mmse_mean_med = "Preop MMSE (mean/med)",
      dm = "Diabetes (%)",
      cardiac = "Cardiac (%)"
      # malnourish = "Malnourished (%)"
    ),
    digits = list(
      age_mean_med ~ 1,
      bmi_mean_med ~ 1,
      female_perc ~ 1,
      asa ~ c(0, 1),
      white ~ 1,
      black ~ 1,
      asian ~ 0,
      # living_independent ~ 1,
      # living_dependent ~ 1,
      # housing_home ~ 1,
      # housing_assisted ~ 1,
      pre_mmse_mean_med ~ 1,
      cog_imp ~ 1,
      dm ~ 1,
      cardiac ~ 1
      # malnourish ~ 1
    ),
    statistic = list(
      age_mean_med ~ "{mean} <u>{median}</u> ({min} - {max})",
      bmi_mean_med ~ "{median} ({min} - {max})",
      female_perc ~ "{median} ({min} - {max})",
      asa ~ "{n} ({p})",
      white ~ "{median} ({min} - {max})",
      black ~ "{median} ({min} - {max})",
      asian ~ "all {median}",
      # living_independent ~ "{mean} ({min} - {max})",
      # living_dependent ~ "{mean} ({min} - {max})",
      # housing_home ~ "{mean} ({min} - {max})",
      # housing_assisted ~ "{mean} ({min} - {max})",
      pre_mmse_mean_med ~ "{mean} ({min} - {max})",
      cog_imp ~ "{mean} ({min} - {max})",
      dm ~ "{mean} ({min} - {max})",
      cardiac ~ "{mean} ({min} - {max})"
      # malnourish ~ "{mean} ({min} - {max})"
    ),
    type = list(
      age_mean_med ~ "continuous",
      bmi_mean_med ~ "continuous",
      female_perc ~ "continuous",
      asa ~ "categorical",
      white ~ "continuous",
      black ~ "continuous",
      asian ~ "continuous",
      # living_independent ~ "continuous",
      # living_dependent ~ "continuous",
      # housing_home ~ "continuous",
      # housing_assisted ~ "continuous",
      pre_mmse_mean_med ~ "continuous",
      cog_imp ~ "continuous",
      dm ~ "continuous",
      cardiac ~ "continuous"
      # malnourish ~ "continuous"
    ),
    # missing_text = "Not reported"
    missing = "no"
  ) |>
  add_n() |>
  modify_header(stat_0 = "**Mean <u>Med</u> (Range) <br/> or N (%)**") |>
  modify_footnote(update = stat_0 ~ NA) |>
  as_gt(id = "one") |>
  cols_width(
    3 ~ px(170),
    # 5 ~ px(60),
    6 ~ px(110)
  ) |>
  fmt_markdown(stat_0) |>
  gt_theme_mg() |>
  tab_style(style = cell_text(align = "left"), locations = cells_body(columns = c(stat_0))) |>
  # tab_footnote("Number of trials reporting from the 9 included (11 publications).", locations = cells_column_labels(columns = c(n)), placement = "right") |>
  # tab_footnote("Mean, median, or range of the mean/med reported in trials.", locations = cells_column_labels(columns = c(stat_0)), placement = "right") |>
  tab_footnote(paste0("N of the ", length(pt_char_tab_refids_rct(kq3_refid)), " studies reporting characteristic allowing description."), locations = cells_column_labels(columns = c(n)), placement = "right") |> 
  tab_footnote("Shin 2020, Li 2022, and Neuman 2021 included patients with dementia.", locations = cells_body(columns = label, rows = label == "Dementia (%)"), placement = "right") |> 
  as_raw_html()

```

## Outcomes

<font size = 4> `r table_ref()` Primary, secondard, and other outcomes. </font>

```{r outcomes}
#| layout: [[33, 33, 33]]
#| echo: false

other_foot <- study_char_dat |> 
  select(out_other_detail) |> 
  filter(!is.na(out_other_detail)) |> 
  mutate(
    out_other_detail = firstup(out_other_detail),
    out_other_detail = str_replace_all(out_other_detail, "acceptibility", "[A]cceptibility"),
    out_other_detail = str_replace_all(out_other_detail, ";$", ""),
    out_other_detail = str_replace_all(out_other_detail, "$", "\\."),
    out_other_detail = paste0(out_other_detail, "<br/>TT"),
    out_other_detail = str_replace_all(out_other_detail, "; B", "; b"),
    out_other_detail = str_replace_all(out_other_detail, "; H", "; h"),
    out_other_detail = str_replace_all(out_other_detail, "homo", "hemo"),
  ) |> 
  pull(out_other_detail) |> 
  toString()

other_foot <- gsub("TT,|TT", "", other_foot)

study_char_dat |> 
  group_by(linked_references_all_refid) |>
  filter(n_enroll == max(n_enroll)) |>
  slice(1) |> 
  ungroup() |>
  select(design_f_abbrev, starts_with("prim_")) |>
  remove_empty(which = "cols") |>
  mutate(across(starts_with("prim"), ~ !is.na(.x))) |>
  rename(
    "Postoperative delirium" = prim_delirium,
    "Delayed neurocognitive recovery" = prim_pocd,
    # "Stroke" = prim_stroke,
    # "Intraoperative awareness" = prim_aware,
    # "Quality of recovery" = prim_recovery,
    # "Depression" = prim_depress,
    "Patient/caregiver satisfaction" = prim_satis,
    # "Valued life activities" = prim_val_life,
    "Functional status (ADL, IADL, mobility)" = prim_function,
    # "HRQoL" = prim_qol,
    "Pain" = prim_pain,
    "Opioid use" = prim_opioid,
    "Complications" = prim_compl,
    "Length of stay" = prim_los,
    # "Discharge location" = prim_dc_loc,
    # "Readmission" = prim_readmit,
    "Mortality (30-, 180-, 365-day)" = prim_mort,
    "Other" = prim_oth
  ) |>
    arrange(design_f_abbrev) |>
    mutate(
      design_f_abbrev = fct_drop(design_f_abbrev)
    ) |>
    group_by(design_f_abbrev) |>
    tbl_summary(
      by = design_f_abbrev,
      missing = "no"
    ) |> 
    modify_header(label = "**Primary Outcome**") |>
    # modify_footnote(update = everything() ~ NA) |>
    as_gt(id = "one") |> 
    cols_width(
      label          ~ px(225),
      stat_1         ~ px(90),
    ) |> 
    gt_theme_mg() |>
    sub_values(values = c("0 (0%)"), replacement = "—") |> 
    tab_footnote(md(other_foot), locations = cells_body(columns = c(stat_1), rows = label == "Other")) 


other_foot <- study_char_dat |> 
  select(sec_oth_specify) |> 
  filter(!is.na(sec_oth_specify)) |> 
  mutate(
    sec_oth_specify = firstup(sec_oth_specify),
    sec_oth_specify = str_replace_all(sec_oth_specify, "acceptibility", "[A]cceptibility"),
    sec_oth_specify = str_replace_all(sec_oth_specify, ";$", ""),
    sec_oth_specify = str_replace_all(sec_oth_specify, "$", "\\."),
    sec_oth_specify = paste0(sec_oth_specify, "<br/>TT"),
    sec_oth_specify = str_replace_all(sec_oth_specify, "; B", "; b"),
    sec_oth_specify = str_replace_all(sec_oth_specify, "; H", "; h"),
    sec_oth_specify = str_replace_all(sec_oth_specify, "homo", "hemo"),
  ) |> 
  pull(sec_oth_specify) |> 
  toString()

other_foot <- gsub("TT,|TT", "", other_foot)

study_char_dat |> 
  group_by(linked_references_all_refid) |>
  filter(n_enroll == max(n_enroll)) |>
  slice(1) |> 
  ungroup() |>
  select(design_f_abbrev, starts_with("sec_")) |>
  select(!starts_with("sec_oth_")) |> 
  remove_empty(which = "cols") |>
  mutate(across(starts_with("sec"), ~ !is.na(.x))) |> # names() -> temp
  rename(
    "Postoperative delirium" = sec_delirium,
    "Delayed neurocognitive recovery" = sec_pocd,
    # "Stroke" = sec_stroke,
    # "Intraoperative awareness" = sec_aware,
    # "Quality of recovery" = sec_recovery,
    # "Depression" = sec_depress,
    "Patient/caregiver satisfaction" = sec_satisfac,
    # "Valued life activities" = sec_val_life,
    "Functional status (ADL, IADL, mobility)" = sec_function,
    "HRQoL" = sec_qol,
    "Pain" = sec_pain,
    "Opioid use" = sec_opioid,
    "Complications" = sec_compl,
    "Length of stay" = sec_los,
    # "Discharge location" = sec_dc_loc,
    "Readmission" = sec_readmit,
    "Mortality (30-, 180-, 365-day)" = sec_mort,
    "Other" = sec_other
  ) |>
    arrange(design_f_abbrev) |>
    mutate(
      design_f_abbrev = fct_drop(design_f_abbrev)
    ) |>
    group_by(design_f_abbrev) |>
    tbl_summary(
      by = design_f_abbrev,
      missing = "no"
    ) |> 
    modify_header(label = "**Secondary Outcome**") |>
    # modify_footnote(update = everything() ~ NA) |>
    as_gt(id = "one") |> 
    cols_width(
      label          ~ px(225),
      stat_1         ~ px(90),
    ) |> 
    gt_theme_mg() |>
    sub_values(values = c("0 (0%)"), replacement = "—") |> 
    tab_footnote(md(other_foot), locations = cells_body(columns = c(stat_1), rows = label == "Other")) 

study_char_dat |> 
  group_by(linked_references_all_refid) |>
  filter(n_enroll == max(n_enroll)) |>
  slice(1) |> 
  ungroup() |>
  select(design_f_abbrev, starts_with("sec_oth_"), -sec_oth_specify) |> # sec_oth_specify is for secondaty
  remove_empty(which = "cols") |>
  mutate(across(starts_with("sec_oth_"), ~ !is.na(.x))) |> # names() -> temp
  rename(
    "Postoperative delirium" = sec_oth_delirium,
    "Delayed neurocognitive recovery" = sec_oth_pocd,
    # "Stroke" = sec_oth_stroke,
    # "Intraoperative awareness" = sec_oth_aware,
    # "Quality of recovery" = sec_oth_recovery,
    "Depression" = sec_oth_depress,
    "Patient/caregiver satisfaction" = sec_oth_satisfac,
    # "Valued life activities" = sec_oth_val_life,
    # "Functional status (ADL, IADL, mobility)" = sec_oth_function,
    # "HRQoL" = sec_oth_qol,
    "Pain" = sec_oth_pain,
    "Opioid use" = sec_oth_opioid,
    "Complications" = sec_oth_compl,
    "Length of stay" = sec_oth_los,
    # "Discharge location" = sec_oth_dc_loc,
    # "Readmission" = sec_oth_readmit,
    # "Mortality (30-, 180-, 365-day)" = sec_oth_mort,
    # "Other" = sec_oth_other
  ) |>
    arrange(design_f_abbrev) |>
    mutate(
      design_f_abbrev = fct_drop(design_f_abbrev)
    ) |>
    group_by(design_f_abbrev) |>
    tbl_summary(
      by = design_f_abbrev,
      missing = "no"
    ) |> 
    modify_header(label = "**Other Outcome**") |>
    # modify_footnote(update = everything() ~ NA) |>
    as_gt(id = "one") |> 
    cols_width(
      label          ~ px(225),
      stat_1         ~ px(90),
    ) |> 
    gt_theme_mg() 
    # sub_values(values = c("0 (0%)"), replacement = "—") |> 
    # tab_footnote(md(other_foot), locations = cells_body(columns = c(stat_1), rows = label == "Other"))

```

