---
title: "Study/Patient Characteristics Expanded Preoperative Evaluation"
date: "`r format(Sys.time(), '%d %B, %Y (%H:%M)')`"
editor: source
toc-title: "**Expanded Preoperative Evaluation**"
toc-location: "left"
cap-location: "top"
toc-depth: 3
page-layout: full
css: styles.css
tables:
  style: Table
caption:
  pre: "Table "
sep: " -- "
---

```{r read_data}
#| include: false
source("code/load_data.R")

# add arm variable to study_arm_dat
study_arm_dat <- data_kq(study_arm_dat, kq1_refid) |>
  mutate(arm = ifelse(arm_kq1_eval == "eval_expand", "Exp", "Std"))

# fix hempenius 2013/2016 linked to include one study
hempenius_2016_arm <- study_arm_dat |> filter(refid == 1263)
hempenius_2013_arm <- study_arm_dat |> filter(refid == 760)
hempenius_2016_char <- study_char_dat |> filter(refid == 1263)
hempenius_2013_char <- study_char_dat |> filter(refid == 760)
hempenius_2013_arm <- coalesce(hempenius_2013_arm, hempenius_2016_arm)
hempenius_2013_char <- coalesce(hempenius_2013_char, hempenius_2016_char)

# linkded
kq1_refid <- kq1_refid[!kq1_refid %in% c(1263, 17156)]

study_char_dat <- study_char_dat |>
  filter(refid %in% kq1_refid) |>
  filter(refid != 760) |>
  bind_rows(hempenius_2013_char) 

study_arm_dat <- study_arm_dat |>
  filter(refid %in% kq1_refid) |>
  filter(refid != 1263) |>
  bind_rows(hempenius_2013_arm)

asa_class <- asa_combine |>
  mutate(asa = str_trim(asa_ps_incl)) |>
  select(refid, asa) |>
  slice(1, .by = "refid")

```

## Randomized Clinical Trials

<font size = 4> `r table_ref()` Study and patient characteristics — randomized clinical trials. </font>

```{r dex_rct}
#| layout: [[35, 30, 35]]

summary_study_char_tab_rct(kq1_refid)

summary_surg_tab_rct(kq1_refid)

## table data ----
pt_char_tab <- study_arm_dat |>
  filter(refid %in% pt_char_tab_refids_rct(kq1_refid)) |> # only kq1 rct
  mutate(
    wgt = arm_n / sum(arm_n, na.rm = TRUE),
    N = sum(arm_n),
    .by = refid
  ) |>
  group_by(refid) |>
  summarize(
    across(
      c(
        age_mean,
        age_med,
        female_perc,
        white,
        black,
        asian,
        bmi_m,
        bmi_med,
        pre_mmse_m,
        pre_mmse_med,
        living_independent,
        living_dependent,
        # housing_home,
        # housing_assisted,
        cog_imp,
        malnourish,
        dm,
        cardiac,
        # cancer,
        # ortho,
        # gi,
        # neuro,
        # pulm,
        # endo,
        # renal,
        # hepatic
      ),
      ~ pt_sum(.x, wgt)
    ),
    N = sum(arm_n)
  ) |>
  mutate(
    age_mean_med = coalesce(age_mean, age_med),
    bmi_mean_med = coalesce(bmi_m, bmi_med),
    pre_mmse_mean_med = coalesce(pre_mmse_m, pre_mmse_med),
  ) |>
  select(-c(bmi_m, bmi_med, pre_mmse_m, pre_mmse_med, age_mean, age_med)) |>
  left_join(asa_class, by = "refid")

## summary table ----
pt_char_tab |>
  select(age_mean_med, bmi_mean_med, female_perc, asa, white, black, asian, living_independent, living_dependent, pre_mmse_mean_med, cog_imp, dm, cardiac, malnourish) |>
  mutate(
    # asian = ifelse(asian == 100, "100%", NA),
    asa = ifelse(asa == "NR", NA, asa),
  ) |>
  tbl_summary(
    label = list(
      age_mean_med = "Age (mean or median)",
      bmi_mean_med = "BMI (mean or median)",
      female_perc = "Female (%)",
      asa = "ASA Physical Status, N (%)",
      white = "White (%)",
      black = "Black (%)",
      asian = "Asian (%)",
      living_independent = "Lives Independently (%)",
      living_dependent = "Lives Dependent (%)",
      # housing_home = "Living at Home (%)",
      # housing_assisted = "Assisted Living (%)",
      cog_imp = "Cognitive Impairment (%)",
      pre_mmse_mean_med = "Preoperative MMSE (mean or median)",
      dm = "Diabetes (%)",
      cardiac = "Cardiac (%)",
      malnourish = "Malnourished (%)"
    ),
    digits = list(
      age_mean_med ~ 1,
      bmi_mean_med ~ 1,
      female_perc ~ 1,
      asa ~ c(0, 0),
      white ~ 1,
      black ~ 1,
      asian ~ 0,
      living_independent ~ 1,
      living_dependent ~ 1,
      # housing_home ~ 1,
      # housing_assisted ~ 1,
      pre_mmse_mean_med ~ 1,
      cog_imp ~ 1,
      dm ~ 1,
      cardiac ~ 1,
      malnourish ~ 1
    ),
    statistic = list(
      age_mean_med ~ "{mean} [<u>{median}</u>] ({min} - {max})",
      bmi_mean_med ~ "{median} ({min} - {max})",
      female_perc ~ "{median} ({min} - {max})",
      asa ~ "{n} ({p})",
      white ~ "{median}",
      # black ~ "          — ",
      black ~ "",
      asian ~ "both {median}",
      living_independent ~ "{mean} ({min} - {max})",
      living_dependent ~ "{mean}",
      # housing_home ~ "{mean} ({min} - {max})",
      # housing_assisted ~ "{mean} ({min} - {max})",
      pre_mmse_mean_med ~ "{mean} ({min} - {max})",
      cog_imp ~ "{mean} ({min} - {max})",
      dm ~ "{mean} ({min} - {max})",
      cardiac ~ "{mean} ({min} - {max})",
      malnourish ~ "{mean}"
    ),
    type = list(
      age_mean_med ~ "continuous",
      bmi_mean_med ~ "continuous",
      female_perc ~ "continuous",
      asa ~ "categorical",
      white ~ "continuous",
      black ~ "dichotomous",
      asian ~ "continuous",
      living_independent ~ "continuous",
      living_dependent ~ "continuous",
      # housing_home ~ "continuous",
      # housing_assisted ~ "continuous",
      pre_mmse_mean_med ~ "continuous",
      cog_imp ~ "continuous",
      dm ~ "continuous",
      cardiac ~ "continuous",
      malnourish ~ "continuous"
    ),
    # missing_text = "Not reported"
  missing = "no"
  ) |>
 add_n() |>
  modify_header(stat_0 = "**Mean <u>Med</u> (Range) <br/> or N (%)**") |>
  modify_footnote(update = stat_0 ~ NA) |>
  as_gt(id = "one") |>
  cols_width(
    3 ~ px(170),
    # 5 ~ px(60),
    6 ~ px(110)
  ) |>
  fmt_markdown(stat_0) |>
  gt_theme_mg() |>
  tab_style(style = cell_text(align = "left"), locations = cells_body(columns = c(stat_0))) |>
  # tab_footnote("Number of trials reporting from the 9 included (11 publications).", locations = cells_column_labels(columns = c(n)), placement = "right") |>
  # tab_footnote("Mean, median, or range of the mean/med reported in trials.", locations = cells_column_labels(columns = c(stat_0)), placement = "right") |>
  tab_footnote(paste0("N of the ", length(pt_char_tab_refids_rct(kq1_refid)), " studies reporting characteristic allowing description."), locations = cells_column_labels(columns = c(n)), placement = "right") |> 
  as_raw_html()

```

## Nonrandomized Studies

<font size = 4> `r table_ref()` Characteristics of nonrandomized studies. </font>

```{r study_char_nrsi}
#| layout: [[35, 30, 35]]

summary_study_char_tab_nrsi(kq1_refid)

summary_surg_tab_nrsi(kq1_refid)

## table data ----
pt_char_tab <- study_arm_dat |>
  filter(refid %in% pt_char_tab_refids_nrsi(kq1_refid)) |> 
  mutate(
    wgt = arm_n / sum(arm_n, na.rm = TRUE),
    N = sum(arm_n),
    .by = refid
  ) |>
  group_by(refid) |>
  summarize(
    across(
      c(
        age_mean,
        age_med,
        female_perc,
        white,
        black,
        asian,
        bmi_m,
        bmi_med,
        pre_mmse_m,
        pre_mmse_med,
        living_independent,
        living_dependent,
        # housing_home,
        # housing_assisted,
        cog_imp,
        malnourish,
        dm,
        cardiac,
        # cancer,
        # ortho,
        # gi,
        # neuro,
        # pulm,
        # endo,
        # renal,
        # hepatic
      ),
      ~ pt_sum(.x, wgt)
    ),
    N = sum(arm_n)
  ) |>
  mutate(
    age_mean_med = coalesce(age_mean, age_med),
    bmi_mean_med = coalesce(bmi_m, bmi_med),
    pre_mmse_mean_med = coalesce(pre_mmse_m, pre_mmse_med),
  ) |>
  select(-c(bmi_m, bmi_med, pre_mmse_m, pre_mmse_med, age_mean, age_med)) |>
  left_join(asa_class, by = "refid")

## summary table ----
pt_char_tab |>
  select(age_mean_med, bmi_mean_med, female_perc, asa, white, black, asian, living_independent, living_dependent, pre_mmse_mean_med, cog_imp, dm, cardiac, malnourish) |>
  mutate(
    # asian = ifelse(asian == 100, "100%", NA),
    asa = ifelse(asa == "NR", NA, asa),
  ) |>
  tbl_summary(
    label = list(
      age_mean_med = "Age (mean or median)",
      bmi_mean_med = "BMI (mean or median)",
      female_perc = "Female (%)",
      asa = "ASA Physical Status, N (%)",
      white = "White (%)",
      black = "Black (%)",
      asian = "Asian (%)",
      living_independent = "Lives Independently (%)",
      living_dependent = "Lives Dependent (%)",
      # housing_home = "Living at Home (%)",
      # housing_assisted = "Assisted Living (%)",
      cog_imp = "Cognitive Impairment (%)",
      pre_mmse_mean_med = "Preoperative MMSE (mean or median)",
      dm = "Diabetes (%)",
      cardiac = "Cardiac (%)",
      malnourish = "Malnourished (%)"
    ),
    digits = list(
      age_mean_med ~ 1,
      bmi_mean_med ~ 1,
      female_perc ~ 1,
      asa ~ c(0, 1),
      white ~ 1,
      black ~ 1,
      asian ~ 0,
      living_independent ~ 1,
      living_dependent ~ 1,
      # housing_home ~ 1,
      # housing_assisted ~ 1,
      pre_mmse_mean_med ~ 1,
      cog_imp ~ 1,
      dm ~ 1,
      cardiac ~ 1,
      malnourish ~ 1
    ),
    statistic = list(
      age_mean_med ~ "{mean} [<u>{median}</u>] ({min} - {max})",
      bmi_mean_med ~ "{median} ({min} - {max})",
      female_perc ~ "{median} ({min} - {max})",
      asa ~ "{n} ({p})",
      white ~ "{median} ({min} - {max})",
      black ~ "{median} ({min} - {max})",
      asian ~ "{median}",
      living_independent ~ "{mean} ({min} - {max})",
      living_dependent ~ "{mean} ({min} - {max})",
      # housing_home ~ "{mean} ({min} - {max})",
      # housing_assisted ~ "{mean} ({min} - {max})",
      pre_mmse_mean_med ~ "{mean} ({min} - {max})",
      cog_imp ~ "{mean} ({min} - {max})",
      dm ~ "{mean} ({min} - {max})",
      cardiac ~ "{mean} ({min} - {max})",
      malnourish ~ "{mean} ({min} - {max})"
    ),
    type = list(
      age_mean_med ~ "continuous",
      bmi_mean_med ~ "continuous",
      female_perc ~ "continuous",
      asa ~ "categorical",
      white ~ "continuous",
      black ~ "continuous",
      asian ~ "continuous",
      living_independent ~ "continuous",
      living_dependent ~ "continuous",
      # housing_home ~ "continuous",
      # housing_assisted ~ "continuous",
      pre_mmse_mean_med ~ "continuous",
      cog_imp ~ "continuous",
      dm ~ "continuous",
      cardiac ~ "continuous",
      malnourish ~ "continuous"
    ),
    # missing_text = "Not reported"
  missing = "no"
  ) |>
    add_n() |>
  modify_header(stat_0 = "**Mean <u>Med</u> (Range) <br/> or N (%)**") |>
  modify_footnote(update = stat_0 ~ NA) |>
  as_gt(id = "one") |>
  cols_width(
    3 ~ px(170),
    # 5 ~ px(60),
    6 ~ px(110)
  ) |>
  fmt_markdown(stat_0) |>  
  gt_theme_mg() |>
  tab_style(style = cell_text(align = "left"), locations = cells_body(columns = c(stat_0))) |>
  tab_footnote(paste0("N of the ", length(pt_char_tab_refids_nrsi(kq1_refid)), " studies reporting characteristic allowing description."), locations = cells_column_labels(columns = c(n)), placement = "right") |> 
  as_raw_html()

```


