---
title: "Study/Patient Characteristics TIVA vs. Inhaled"
date: "`r format(Sys.time(), '%d %B, %Y (%H:%M)')`"
editor: source
toc-title: "**Characteristics**"
toc-location: "left"
cap-location: "top"
toc-depth: 3
page-layout: full
css: styles.css
tables:
      style: Table
      caption:
        pre: "Table "
        sep: " -- "
---

```{r read_data}
#| include: false
source("code/load_data.R")

study_char_dat <- data_kq(study_char_dat, kq4_refid) |> 
  mutate(
  surgs = ifelse(str_count(surgs, "\\|") > 3 | str_detect(surgs, "Various"), "Various", surgs))

study_arm_dat <- data_kq(study_arm_dat, kq4_refid) |> 
  mutate(arm = ifelse(arm_kq4_iv_inhale == "tiva", "TIVA", "Inhaled"))

```

```{r specfic_functions}
n_per_tf <- function(var_name, n_dig = 1){
  paste0(sum(var_name == TRUE, na.rm = TRUE), " (", format(round(100*(mean(var_name, na.rm = TRUE)), n_dig), nsmall = 1), ")")
}
```

### Randomized Trial Characteristics 

<font size = 4> `r table_ref()` Characteristics of randomized controlled trials. </font>

```{r studyChar}
study_char_tab <- study_char_dat |> 
  filter(design == "rct") |> 
  mutate(
    dates = str_c(date_start, "-", date_end),
    country = countrycode::countryname(country, destination = "un.name.en"),
    country = ifelse(grepl("United States", country), "United States", country),
    country = ifelse(grepl("United Kingdom", country), "United Kingdom", country),
    country = ifelse(grepl("Republic of Korea", country), "South Korea", country),
    country = ifelse(grepl("Iran", country), "Iran", country),
    country = ifelse(grepl("Türkiye", country), "Turkey", country),
    eu = countrycode::countryname(country, destination = "eu28"),
    un = countrycode::countryname(country, destination = "un.region.name"),
    asia = un == "Asia",
    eu = eu == "EU",
    afr = un == "Africa",
    us = grepl("United States", country),
    ca = grepl("Canada", country),
    sa = grepl("Brazil", country),
    noneu = grepl("Bosnia|Kosovo", country),
    low_r = if_else(non_vh_hdi == "yes", 1, 0, missing = 0),
    pilot = if_else(pilot == "yes", 1, 0, missing = 0),
    ambulatory = !is.na(ambulatory),
    one_center = centers == 1,
    multi_center = centers > 1,
    general = !is.na(general),
    regional = !is.na(regional),
    sedation = !is.na(sedation),
    non_vh_hdi = ifelse(is.na(non_vh_hdi), 0, 1),
    fund_ind = funding == "industry",
    fund_pubind = funding == "pub_indus",
    fund_pub = funding == "public",
    fund_nr = funding == "NR",     
    auth_coi = author_coi == "author_coi",
    registered = if_else(registered == "yes", TRUE, FALSE, missing = FALSE),
  ) |> 
  select(refid, study, eu, un, country, asia, eu, us, ca, sa, noneu, afr, low_r, non_vh_hdi, pilot, ambulatory, one_center, multi_center, general, regional, sedation, starts_with("fund_"), registered, n_enroll, arms, auth_coi) 
  
countries <- study_char_tab |> 
  tabyl(country) |> 
  arrange(desc(n)) |> 
  mutate(
  n_per = paste0(n, " (", round(percent * 100, 1), ")"),
  characteristic = paste0("  ", country)
  ) |> 
  select(characteristic, n_per)

anesthetic <- study_arm_dat |> 
  group_by(refid) |> 
  slice(1) |> 
  ungroup() |> 
  mutate(
    volatile = if_any(c(vol_desflurane, vol_halothane, vol_isoflurane, vol_sevoflurane, vol_ns), ~ !is.na(.x)),
    tiva = ifelse(str_detect(anesth_type, "tiva"), TRUE, FALSE)
    # volatile = kq4_gen_type %in% c("inhalation", "tiva_inhal"),
    # tiva = kq4_gen_type %in% c("tiva", "tiva_inhal")
  ) |> 
  select(refid, volatile, tiva)

table <- study_char_tab |> 
  left_join(anesthetic, by = "refid") |> 
  summarize(
    "Number of Trials" = n(),
    "Patients Enrolled (N)" = " ",
    "  Mean" = round(mean(n_enroll), 0),
    "  Median" = median(n_enroll),
    "  Range" = paste0("(", min(n_enroll), "-", max(n_enroll), ")"),
    "Arms" = " ",
    "  Two" = sum(arms == 2, na.rm = TRUE),
    "  Multi" = sum(arms > 2, na.rm = TRUE),
    "  Mean " = round(mean(arms, na.rm = TRUE), 1),
    "  Median " = round(median(arms, na.rm = TRUE), 1),
    "  Range " = paste0("(", min(arms, na.rm = TRUE), "-", max(arms, na.rm = TRUE), ")"),
    "Pilot Study" = n_per_tf(pilot),
    "Ambulatory" = n_per_tf(ambulatory),
    "Centers" = " ",
    "  Single Center" = n_per_tf(one_center),
    "  Multicenter" = n_per_tf(multi_center),
    # "Anesthesia" = " ",
    "Volatile Anesthetic" = n_per_tf(volatile),
    # "  TIVA" = n_per_tf(tiva),
    # "  Sedation" = n_per_tf(sedation),
    "Country" = " ",
    "Non-very-high HDI Countryª" = n_per_tf(low_r),
    # expression(paste("Non-very-high HDI"^"a")) = n_per_tf(low_r),
    "Funding" = " ",
    "  Industry" = n_per_tf(fund_ind),
    "  Public/Industry" = n_per_tf(fund_pubind),
    "  Public" = n_per_tf(fund_pub),
    "  Not Reported" = n_per_tf(fund_nr),     
    "Author COI" = n_per_tf(auth_coi),
    "Registered" = n_per_tf(registered),
  ) |>
  t() |> 
  data.frame() %>% 
  rename(n_per = 1) |> 
  mutate(
  n = str_extract(n_per, "^\\d{1,2}"),
  per = str_extract(n_per, "\\(\\d{1,2}\\.\\d\\)")) |> 
  rownames_to_column(var = "characteristic") |> 
  select(characteristic, n_per) |> 
  remove_rownames()

table <- table |> 
  add_row(countries, .after = 18)

table |> 
  gt(id = "one") |>
  fmt_integer(use_seps = TRUE, sep_mark = ",") |>
  cols_label(
    characteristic   = "Characteristic",
    n_per            = "N (%)",
  ) |>
  cols_width(
    characteristic ~ px(240),
    n_per ~ px(150)
  ) |> 
 gt_theme_mg() 

writexl::write_xlsx(table, "/Users/mgrant/Desktop/study_char_rct_tab_kq4.xlsx")

```

<br/>

### Patient Charcteristics

<br/>

<font size = 4> `r table_ref()` Patient characteristics in randomized controlled trials. </font>

```{r ptCharRev}
#| warning: false
## (updated 2021/07/21 08:26) surgery type --------------------------------
# surg <- study_char.dat |>
#   filter(
#     design %in% c("rct", "crossover"),
#     age == "Adult",
#     refid %in% rev_refids,
#   ) |>
#   mutate(
#     across(surg_various:surg_other, ~ str_replace(.x, "surg_", "")),
#     across(surg_various:surg_other, ~ str_c(.x, ", ")),
#     across(surg_various:surg_other, ~ firstup(.x)),
#     across(surg_various:surg_other, ~ replace_na(.x, "")),
#     surg_list = ifelse(grepl("abdom", surg_list), "Abdominal, ", ""),
#     surgs = str_c(surg_various, surg_car, surg_cr, surg_gyn, surg_gi, surg_gen, surg_headneck, surg_hep, surg_neuro, surg_opth, surg_oralmax, surg_ortho, surg_otolar, surg_plastic, surg_thor, surg_urol, surg_other, surg_list),
#     surgs = str_replace(surgs, "Otolar", "ENT"),
#     surgs = str_replace(surgs, "Headneck", "ENT"),
#     surgs = str_sub(surgs, 1, nchar(surgs) - 2),
#     surgs = ifelse(str_count(surgs, ",") > 2, "Various", surgs)
#     ) |>
surg <- surgs |> 
  select(refid, surgs_single) |> 
  rename(surgs = surgs_single) |> 
  tabyl(surgs) |> 
  arrange(desc(percent)) |> 
  rename(per = percent) |> 
  mutate(per = paste0( "(", format(round(100*per, 1), nsmall = 1), ")"),
         per = str_replace(per, " ", ""),
         n = as.character(n),
         n_per = paste(n, per)) |> 
  select(surgs, n_per) |> 
  rename(result = n_per, characteristic = surgs) |> 
  remove_rownames() |> 
  mutate(
    characteristic = str_replace(characteristic, "Gi", "GI"),
    characteristic = str_replace(characteristic, "Cr", "CR"),
    characteristic = ifelse(characteristic == "Various", "Various (>3)", characteristic),
    characteristic = paste0("  ", characteristic),
  )

asa_class <- asa_combine |>
  mutate(asa = str_trim(asa_ps_incl)) |>
  select(refid, asa) |> 
  slice(1, .by = "refid")

pt_char_tab <- study_arm_dat |>
  filter(design_f == "Randomized Clinical Trial") |> 
  # filter(
  #   design %in% c("rct", "crossover"),
  #   age == "Adult",
  #   refid %in% rev_refids) |> 
  group_by(refid) |>
  summarize(
    N = sum(arm_n),
    wgt = arm_n / N,
    # asa_12_all = round(sum(asa  == "12" * wgt, na.rm = FALSE)),
    # asa_123_all = round(sum(asa = "123" * wgt, na.rm = FALSE)),
    # asa_23_all = round(sum(asa = "23" * wgt, na.rm = FALSE)),
    # asa_34_all = round(sum(asa_34 * wgt, na.rm = FALSE)),
    age_mn_all = round(sum(age_mean * wgt, na.rm = FALSE)),
    age_md_all = round(sum(age_med * wgt, na.rm = FALSE)),
    sex_all = round(sum(female_perc * wgt, na.rm = FALSE)),
    white_all = round(sum(white * wgt, na.rm = FALSE)),
    black_all = round(sum(black * wgt, na.rm = FALSE)),
    asian_all = round(sum(asian * wgt, na.rm = FALSE)),
    bmi_mn_all = round(sum(bmi_m * wgt, na.rm = FALSE)),
    bmi_md_all = round(sum(bmi_med * wgt, na.rm = FALSE)),
    dm_mn_all = round(sum(dm * wgt, na.rm = FALSE)),
    neuro_all = round(sum(neuro * wgt, na.rm = FALSE))) |>
  filter(row_number() == 1) |>
  ungroup() |> 
  rename_with(~ str_replace(., "_all", "")) |> 
  # mutate(across(asa_1:asa_34, ~ replace(., !is.na(.), "Y")),
  #        across(asa_1:asa_34, ~ replace(., is.na(.),  "-")),
  #        ) |> 
  # unite(col = "asa", asa_1:asa_34, sep = "", remove = FALSE) |> 
  mutate(
    age = case_when(
      !is.na(age_mn) ~ age_mn,
      !is.na(age_md) ~ age_md,
    ),
    bmi = case_when(
      !is.na(bmi_mn) ~ bmi_mn,
      !is.na(bmi_md) ~ bmi_md,
    ),
  ) |> 
  left_join(asa_class, by = c("refid")) |> 
  summarise(
    "Age (average of mean or med, range)" = paste0(round(sum(age/(n() - sum(is.na(age_mn) & is.na(age_md))), na.rm = TRUE), 1), " (", min(age, na.rm = TRUE), "-", max(age, na.rm = TRUE), ")"),
    "Female (%, range)" = paste0(round(sum(sex, na.rm = TRUE)/(n() - sum(is.na(sex))), 1), " (", min(sex, na.rm = TRUE), "-", max(sex, na.rm = TRUE), ")"),
    "ASA Physical Status (%)" = " ",
    "  I-II" =   round(100 * mean(asa == "12"), 1),
    "  I-III" =  round(100 * mean(asa == "123"), 1),
    "  I-IV" =  round(100 * mean(asa == "1234"), 1),
    "  II-IV" =  round(100 * mean(asa == "234"), 1),
    "  II-III" =  round(100 * mean(asa == "23"), 1),
    "  III" =  round(100 * mean(asa == "3"), 1),
    "  III-IV" =  round(100 * mean(asa == "34"), 1),
    "  NR"     = round(100*mean(asa == "NR"), 1), 
    "BMI (average of mean or med, range)" = paste0(round(sum(bmi/(n() - sum(is.na(bmi_mn) & is.na(bmi_md))), na.rm = TRUE), 1), " (", min(bmi, na.rm = TRUE), "-", max(bmi, na.rm = TRUE), ")"),
    "BMI (mean or med ≥ 30), (%)" = paste0("(", round(sum(bmi >= 30, na.rm = TRUE) / n() * 100, 1), ")"),
    # "DM" = " ",
    # "  Any (studies)" = sum(dm_mn > 0, na.rm = TRUE),
    # "    % pts, (range)" = paste0("(", min(dm_mn[dm_mn != 0], na.rm = TRUE), "-", max(dm_mn, na.rm = TRUE), ")")
  ) |> 
t() |> 
  data.frame() |> 
  rownames_to_column(var = "characteristic") |> 
  rename(result = 2) |> 
  remove_rownames() |> 
  add_row(characteristic = "Surgery, N (%)", result = "") |> 
  # add surgery type
  bind_rows(surg)

pt_char_tab |>
  gt(id = "one") |>
  cols_label(
    characteristic   = "Characteristic",
    result           = "N (%) or Value",
  ) |>
  cols_width(
    characteristic ~ px(240),
    result ~ px(150)
  ) |> 
 gt_theme_mg()
  
writexl::write_xlsx(pt_char_tab, "/Users/mgrant/Desktop/pt_char_tab.xlsx")

```
